# Generated by Django 4.1.5 on 2023-01-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Brand name"),
        ),
    ]
