# Generated by Django 4.1.5 on 2023-01-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScraperRealtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=250)),
                ("size", models.IntegerField()),
                ("built", models.BigIntegerField()),
                ("rooms", models.IntegerField()),
                ("garage", models.BooleanField()),
                ("description", models.TextField()),
            ],
        ),
    ]
